### ISSUE TITLE
webrtc xcode bindings

### ISSUE THREAD

**Issue by RnbWd** [feross/WebTorrent.app#1]
https://github.com/pristineio/webrtc-build-scripts

If anyone with more xcode experience than myself is able create bindings with for `react-native` in a way that replicates the protocol used in https://github.com/feross/simple-peer for node - then webtorrent could extend into the iOS world - potentially built on top of everything that already exists in this world.

**Comment by feross** [comment]
Why is `react-native` necessary?

**Comment by RnbWd** [comment]
The [native modules](https://facebook.github.io/react-native/docs/nativemodulesios.html#content) section have libraries that at first glance seem similar `node-gyp`, but for objC / Swift. I hypothesize that similar techniques used by [node-webrtc](https://github.com/js-platform/node-webrtc) to mimic the browser's in webRTC API could be implemented.

`react-native` isn't the only JS-to-mobile framework, but it's the most powerful, accessible (and fun to use) I've come across, with decent documentation for ObjC / JS interop. I'm open to other idea's for bringing this to iOS, but I think it's actually possible..

**Comment by feross** [comment]
This is a cool idea. I haven't used react-native, but I have friends who have. They have nothing but good things to say about it. If we could make really easy bindings then more people would build apps that use WebRTC on mobile.

This isn't something I'm going to work on soon, but feel free to keep us updated in this issue.
